#!/bin/bash
#	 Upanix - An x86 based Operating System
#	 Copyright (C) 2011 'Prajwala Prabhakar' 'srinivasa.prajwal@gmail.com'
#
# I am making my contributions/submissions to this project solely in
# my personal capacity and am not conveying any rights to any
# intellectual property of any third parties.
#																			 
#	 This program is free software: you can redistribute it and/or modify
#	 it under the terms of the GNU General Public License as published by
#	 the Free Software Foundation, either version 3 of the License, or
#	 (at your option) any later version.
#																			 
#	 This program is distributed in the hope that it will be useful,
#	 but WITHOUT ANY WARRANTY; without even the implied warranty of
#	 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	 GNU General Public License for more details.
#																			 
#	 You should have received a copy of the GNU General Public License
#	 along with this program.  If not, see <http://www.gnu.org/licenses/

#Customized Qemu Run Script -- Self Written
clear

LOAD_BINARY=$1

if [ "$LOAD_BINARY" = "load" ]
then
  $UPANIX_HOME/build_load.sh
  if [ $? -ne 0 ]
  then
    exit 1
  fi
fi

if [ "$BOOT_USB_DEVICE_NAME" = "" -a "$BOOT_USB_DEVICE_ID" != "" ]
then
  devicename=`udevadm info --query=all -n disk/by-id/$BOOT_USB_DEVICE_ID | grep "^N:" | cut -d":" -f2 | tr -d " "`
  if [ $? -eq 0 ]
  then
    BOOT_USB_DEVICE_NAME=$devicename
  fi
fi

if [ "$BOOT_USB_DEVICE_NAME" = "" ]
then
  BOOT_DRIVE="$UPANIX_HOME/USBImage/300MUSB.img"
else
  BOOT_DRIVE="/dev/$BOOT_USB_DEVICE_NAME"
fi

echo -e "\n\n*****************************************************************************\n\n"
echo -e "					Booting from `basename $BOOT_DRIVE`"
echo -e "\n\n*****************************************************************************\n\n"

sleep 1

#-hda $UPANIX_HOME/USBImage/30MUSB.img
#-usbdevice disk:$UPANIX_HOME/USBImage/30MUSB.img
#-hda /dev/sda \
#
#-drive if=none,id=usbdrive,file=/dev/sdb \
#-drive if=none,id=usbdrive,file=$UPANIX_HOME/USBImage/300MUSB.img \

#-netdev user,id=u1 -device e1000,netdev=u1 \
#-object filter-dump,id=f1,netdev=u1,file=dump.dat \
#-netdev tap,ifname=tap0,script=no,downscript=no,id=mynet0 \
#-device e1000,netdev=mynet0,mac=00:00:00:11:11:11 \
#
#-net nic,model=e1000 \
#-net tap,ifname=tap0,script=no,downscript=no \
#
#-netdev vmnet-bridged,id=net0,ifname=en0 \
#-device virtio-net,netdev=net0 \
#
#~/workspace/tools/qemu/build/qemu-system-x86_64 \
# -s -S \ -> for debugging. -s is localhost:1234, -S is pause until lldb/gdb connection


#Use this if you want to use EHCI for boot-drive and XHCI for the other attached USB drive
#-drive if=none,id=usbbootdrive,file=$BOOT_DRIVE,file.locking=off,format=raw,cache=writeback \
#-device usb-ehci,id=ehci \
#-device usb-storage,bus=ehci.0,drive=usbbootdrive \
#-drive if=none,id=usbdrive1,file=$UPANIX_HOME/USBImage/300MUSB_ehci.img,file.locking=off,format=raw \
#-device nec-usb-xhci,id=xhci \
#-device usb-storage,bus=xhci.0,port=1,drive=usbdrive1 \
#-device usb-hub,bus=xhci.0,port=3 \

#Use this if you want to use XHCI for boot-drive and also the other attached USB drive
#-drive if=none,id=usbbootdrive,file=$BOOT_DRIVE,file.locking=off,format=raw,cache=writeback \
#-drive if=none,id=usbdrive1,file=$UPANIX_HOME/USBImage/300MUSB_ehci.img,file.locking=off,format=raw \
#-device nec-usb-xhci,id=xhci \
#-device usb-storage,bus=xhci.0,port=1,drive=usbbootdrive \
#-device usb-storage,bus=xhci.0,port=2,drive=usbdrive1 \
#-device usb-hub,bus=xhci.0,port=3 \

sudo -S echo "starting qemu" < .sudopass
sudo qemu-system-x86_64 \
-serial file:serial_debug.log \
-drive if=pflash,file=$UPANIX_TOOLS/OVMF.fd,format=raw \
-m 512 \
-s \
-smp 1 \
-usb \
-drive if=none,id=usbbootdrive,file=$BOOT_DRIVE,file.locking=off,format=raw \
-device usb-ehci,id=ehci \
-device usb-storage,bus=ehci.0,drive=usbbootdrive \
-drive if=none,id=usbdrive1,file=$UPANIX_HOME/USBImage/300MUSB_ehci.img,file.locking=off,format=raw \
-device nec-usb-xhci,id=xhci \
-device usb-storage,bus=xhci.0,port=1,drive=usbdrive1 \
-device usb-hub,bus=xhci.0,port=3 \
-nic tap,model=e1000,ifname=tap0,script=./tap_net_up.sh,downscript=./tap_net_down.sh
#-nic user,model=e1000

#-nic option allows you to have guest directly connect to host backend without an intermediate hub valn
#-nic tap,model=e1000,ifname=tap0,script=./tap_net_up.sh,downscript=./tap_net_down.sh

# setting up networking using below options will use an intermediate hub vlan -
# where in the emulated NIC (front-end) on the guest is not directly connected to the host-backend
#-net nic,model=e1000 \
#-net tap,ifname=tap0,script=./tap_net_up.sh,downscript=./tap_net_down.sh
